[features]
seeds = false
skip-lint = false
[programs.devnet]
gifkit = "AxBKG2ku3PqVYfQp9rZBU4tuNDLjZ7dxLxJqC8MndTe3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/paulo/.config/solana/id.json"

[scripts]
test = "node tests/gifkit.js"
